services:
  - type: web
    name: thesis-implementation
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn thesis_project.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: thesis_project
          property: connectionString
